spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board
    username: root
    password: 1q2w3e4r

  mail:
    host: smtp.gmail.com
    port: 587
    username: jw7812@gmail.com
    password: xfsfenderpcnrkwx
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

mybatis:
  mapper-locations:
    - /mappers/*.xml

jwt:
  secret: Ol0dMza3CsYJVfIdSBLudSwfc5MWqJaOrO+R5TPAoOlthLZ4AksrHQkgxgVPfSQ8lGGnRY6R7w9ER1nNpuuj4A==
